use std::path::PathBuf;
use std::sync::mpsc::Sender;
use std::thread::JoinHandle;

#[derive(Clone)]
pub struct ProviderOption {
    pub name: String,
    pub slot: String,
    pub env_var: String,
    pub base_url: String,
}

pub enum BindingEvent {
    ChatDetected { username: String, chat_id: String },
    CodeMatched { chat_id: String },
    Error(String),
}

/// Menyimpan konfigurasi model router TOML dan API key / token ke file .env di disk.
pub fn save_config_to_disk(
    config_path: &PathBuf,
    provider: &ProviderOption,
    custom_model: &str,
    custom_url: &str,
    api_key: &str,
    telegram_token: &str,
    telegram_chat_id: &str,
) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
    let config = if provider.slot == "custom" {
        format!(
            "# Claw10 OS configuration\n\
             # Generated by `claw10 setup`\n\n\
             [custom.my-provider]\n\
             base_url = \"{url}\"\n\
             api_key = \"${env_var}\"\n\
             models = [\"{model}\"]\n\n\
             [alias.default]\n\
             slot = \"my-provider\"\n\
             model = \"{model}\"\n\
             api_key = \"${env_var}\"\n",
            url = custom_url,
            env_var = provider.env_var,
            model = custom_model,
        )
    } else {
        format!(
            "# Claw10 OS configuration\n\
             # Generated by `claw10 setup`\n\n\
             [alias.default]\n\
             slot = \"{slot}\"\n\
             model = \"{model}\"\n\
             api_key = \"${env_var}\"\n",
            slot = provider.slot,
            model = custom_model,
            env_var = provider.env_var,
        )
    };

    if let Some(parent) = config_path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(config_path, config)?;

    // Simpan API key dan Telegram Bot Token ke file .env
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
    let env_dir = PathBuf::from(&home).join(".claw10");
    std::fs::create_dir_all(&env_dir)?;

    let mut env_content = String::new();
    if !api_key.is_empty() {
        env_content.push_str(&format!("{}={}\n", provider.env_var, api_key));
    }
    if !telegram_token.is_empty() {
        env_content.push_str(&format!("TELEGRAM_BOT_TOKEN={}\n", telegram_token));
    }
    if !telegram_chat_id.is_empty() {
        env_content.push_str(&format!("TELEGRAM_CHAT_ID={}\n", telegram_chat_id));
    }

    let env_path = env_dir.join(".env");
    std::fs::write(env_path, env_content)?;

    Ok(())
}

/// Men-spawn thread background untuk mendengarkan getUpdates Telegram bot secara realtime
pub fn spawn_telegram_polling_thread(
    token: String,
    code: String,
    tx: Sender<BindingEvent>,
) -> JoinHandle<()> {
    std::thread::spawn(move || {
        let client = match reqwest::blocking::Client::builder()
            .timeout(std::time::Duration::from_secs(4))
            .build()
        {
            Ok(c) => c,
            Err(e) => {
                let _ = tx.send(BindingEvent::Error(format!("Gagal inisialisasi HTTP client: {e}")));
                return;
            }
        };

        // Hapus webhook aktif agar API getUpdates bisa berfungsi dengan benar
        let del_url = format!("https://api.telegram.org/bot{}/deleteWebhook", token);
        let _ = client.get(&del_url).send();

        let mut offset = 0i64;
        let mut detected_chat_id: Option<String> = None;

        loop {
            let url = format!(
                "https://api.telegram.org/bot{}/getUpdates?offset={}&timeout=3",
                token, offset
            );
            match client.get(&url).send() {
                Ok(res) => {
                    if let Ok(json) = res.json::<serde_json::Value>() {
                        if let Some(ok) = json.get("ok").and_then(|v| v.as_bool()) {
                            if ok {
                                if let Some(result) = json.get("result").and_then(|v| v.as_array()) {
                                    for update in result {
                                        if let Some(update_id) = update.get("update_id").and_then(|v| v.as_i64()) {
                                            offset = update_id + 1;
                                        }
                                        if let Some(message) = update.get("message") {
                                            if let Some(chat) = message.get("chat") {
                                                if let Some(chat_id) = chat.get("id").map(|v| v.to_string()) {
                                                    let username = chat.get("username")
                                                        .and_then(|v| v.as_str())
                                                        .unwrap_or("User")
                                                        .to_string();
                                                    
                                                    let text = message.get("text")
                                                        .and_then(|v| v.as_str())
                                                        .unwrap_or("")
                                                        .trim()
                                                        .to_string();

                                                    // Jika pesan mengandung kode verifikasi secara persis, langsung trigger CodeMatched!
                                                    if text == code || text.contains(&code) {
                                                        let _ = tx.send(BindingEvent::CodeMatched { chat_id });
                                                        return; // Stop thread
                                                    }

                                                    if detected_chat_id.is_none() {
                                                        detected_chat_id = Some(chat_id.clone());
                                                        let _ = tx.send(BindingEvent::ChatDetected { username, chat_id: chat_id.clone() });
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            } else {
                                let desc = json.get("description").and_then(|v| v.as_str()).unwrap_or("Unknown error");
                                let _ = tx.send(BindingEvent::Error(format!("Telegram API Error: {desc}")));
                                return;
                            }
                        }
                    }
                }
                Err(_) => {}
            }
            std::thread::sleep(std::time::Duration::from_millis(500));
        }
    })
}

/// Mengambil list model dari provider terdaftar menggunakan HTTP Request
pub fn fetch_provider_models(
    base_url: &str,
    api_key: &str,
) -> Result<Vec<String>, Box<dyn std::error::Error + Send + Sync>> {
    let client = reqwest::blocking::Client::builder()
        .timeout(std::time::Duration::from_secs(5))
        .build()?;

    let url = format!("{}/models", base_url);
    let res = client
        .get(&url)
        .header("Authorization", format!("Bearer {}", api_key))
        .header("Accept", "application/json")
        .send()?;

    if !res.status().is_success() {
        return Err(format!("HTTP Error {}", res.status()).into());
    }

    let json: serde_json::Value = res.json()?;
    let mut models = Vec::new();

    if let Some(data) = json.get("data").and_then(|v| v.as_array()) {
        for entry in data {
            if let Some(id) = entry.get("id").and_then(|v| v.as_str()) {
                models.push(id.to_string());
            }
        }
    }

    if models.is_empty() {
        return Err("Tidak ada model ditemukan atau format respons tidak sesuai.".into());
    }

    Ok(models)
}
